name: Fetch Taiwan Weather Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  fetch-weather:
    runs-on: ubuntu-latest
    environment: CWB_crawler

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch weather data
        env:
          CWB_API_KEY: ${{ secrets.CWB_API_KEY }}
        run: |
          python cwa_now_data_crawler.py

      - name: Commit & push data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch
          git checkout feature/get-data-crawler
          git merge main
          git add now_data_github/
          git commit -m "Auto-update weather data"
          git push origin feature/get-data-crawler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
